// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpSqoXsZjIE5ldinr_JGh3rImfa3Y05fs',
    appId: '1:303056166255:web:adc0181aed9e887837dc9a',
    messagingSenderId: '303056166255',
    projectId: 'auth-9a286',
    authDomain: 'auth-9a286.firebaseapp.com',
    storageBucket: 'auth-9a286.appspot.com',
    measurementId: 'G-GGKMVVS0RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7D0Ujpfwqzmb0QQy33UrexKw_Or48DIg',
    appId: '1:303056166255:android:f5a74e7e8ccac7ba37dc9a',
    messagingSenderId: '303056166255',
    projectId: 'auth-9a286',
    storageBucket: 'auth-9a286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmP-qvWIgTwfkebHNmn59Qj3S3zIXRVXI',
    appId: '1:303056166255:ios:5ffad77611b6842c37dc9a',
    messagingSenderId: '303056166255',
    projectId: 'auth-9a286',
    storageBucket: 'auth-9a286.appspot.com',
    iosBundleId: 'com.jv.auth',
  );
}
